# Generated by Django 6.1.2 on 2026-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='images_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='pdf_ms',
            field=models.FloatField(default=0),
        ),
    ]
