# Generated by Django 5.2.18 on 2026-10-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generationrun_images_ms_generationrun_pdf_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerun',
            name='align_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='imagerun',
            name='deskew_applied',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imagerun',
            name='skew_angle',
            field=models.FloatField(default=0),
        ),
    ]
