# Generated by Django 5.2.18 on 2026-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagerun_align_method_imagerun_deskew_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerun',
            name='steps',
            field=models.JSONField(default=list),
        ),
    ]
